---
- hosts: ubuntu_servers
  become: True
  vars:
    ips: "{{ groups['ubuntu_servers'] | map('extract',hostvars,['ansible_host']) | join(';') }}"

  tasks:

    - name: install fail2ban package
      apt: 
        name: fail2ban
        state: present
      notify: start fail2ban

    - name: change configuration file
      lineinfile:
        path: /etc/fail2ban/jail.conf
        regexp: '^ignoreip = '
        line: "ignoreip = {{ ips }}"
      notify: reload fail2ban

  handlers:
    - name: start fail2ban
      service:
        name: fail2ban
        enabled: true
        state: started

    - name: reload fail2ban
      service:
        name: fail2ban
        state: reloaded
      changed_when: False

