---
- hosts: all
  become: True
  vars:
    ubuntu_user: ubuntu
    centos_user: ec2-user
  tasks:
    - name: copying ssh key to remote host
      ansible.posix.authorized_key:
        user: '{{ ubuntu_user }}'
        state: present
        key: "{{ lookup('file', item) }}"
      with_fileglob:
        - /home/ubuntu/Ansible/task2/SSH_KEYS/*.pub
      when: ansible_distribution == "Ubuntu"
