---
- hosts: all
  become: True
  vars:
    keys_path: /home/ubuntu/Ansible/task2/SSH_KEYS/

  tasks:
    - name: set fact for Ubuntu
      set_fact:
        user: ubuntu
      when: ansible_distribution == "Ubuntu"
        
    - name: set fact for CentOS
      set_fact:
        user: ec2-user
      when: ansible_distribution == "CentOS"

    - name: copying ssh key to remote host for Ubuntu
      ansible.posix.authorized_key:
        user: '{{ user }}'
        state: present
        key: "{{ lookup('file', item) }}"
      with_fileglob:
        - "{{ keys_path }}*.pub"
      register: out


